### PR TITLE
format.py 

### PR DESCRIPTION
**Pull request by anamika-yadav99**

### CODE REVIEW

**Comment by manulera** [comment]
Hello Anamika,

There a few problems that need fixing:

* [ ] `Lab_strains/dey_lab/format.py` no longer solves #16 you should revert to this version: https://github.com/manulera/genestorian_data_refinement/pull/20/commits/97a4d5b118e15a774e2e717af16efd7001acc843
* [ ] You should delete the following files (I think you are not using them):
  * [ ] `genestorian_module/genestorian_module/Identifiers/identifiers.toml`
  * [ ] `genestorian_module/genestorian_module/generic_func.py`
* [ ] This file should be empty: `genestorian_module/genestorian_module/__init__.py`
* [ ] Line 18 in `get_data/convert_gene2toml.py` should also check whether the field is empty. Note that the current version generates empty names:
    https://github.com/manulera/genestorian_data_refinement/blob/03b6cb79fb3d323228cf165f326b4e61930e6d0f/data/gene_IDs.toml#L29-L32

**Comment by manulera** [comment]
Also, which script is addressing the second part of #16 ?
  * A python script that:
    * Takes `Lab_strains/dey_lab/strains.tsv` and `data/alleles.toml` as an input and replaces the allele names by

**Comment by manulera** [comment]
I think some of it might have been buried in some previous commit, that you accidentally overwrote, we can try to dig for it together.

**Comment by anamika-yadav99** [comment]
I'm currently working in generic.py to write a generalized function issue #19 . Will soon push it to the repo.

**Comment by anamika-yadav99** [comment]
> Also, which script is addressing the second part of #16 ?
> 
> * A python script that:
>   
>   * Takes `Lab_strains/dey_lab/strains.tsv` and `data/alleles.toml` as an input and replaces the allele names by

format.py. But instead of text I have it in json.  I can make it to write in a txt file if you want.

**Pull request closed without merging**
