### PR TITLE
Nltk trees manu

### PR DESCRIPTION
**Pull request by manulera**
All my changes to be merged into your branch

### CODE REVIEW

**Comment by anamika-yadav99** [comment]
Hi @manulera ! I looked though the code and  I ran the code on nbrp strains and it's not working as expected. 
Some examples:

-   "leu1-32:pnpg1-npg1-gfp-tadh1-ura4+": "(ROOT (ALLELE leu1-32) (- :) (PROMOTER_GENE (other p) (GENE npg1)) (- -) (GENE npg1) (- -) (TAG gfp) (- -) (PROMOTER_GENE (other t) (GENE adh1)) (- -) (ALLELE ura4+))"
-    "ade6-m210<<ade6+:mfm1-k34stop": "(ROOT (ALLELE ade6-m210) (- <<) (ALLELE_AA_SUBSTITUTION (GENE ade6) (other +)) (- :) (ALLELE_AA_SUBSTITUTION (GENE mfm1) (- -) (other k34s)) (other top))",
 
The reason why this is happening is because these false patterns do follow the chunker rule so they have label of the chunk rule they match to but the value of other tag doesn't match so they are actually false matches. These trees have to be deleted if the value of the other tag doesn't match.

**Comment by manulera** [comment]
Hi @anamika-yadav99, I noticed that that pattern fails and picks up wrong things. I thikn it's probably the regex pattern. You can have a look and see if you figure it out. You can debug it more easily here: https://regex101.com/

**Comment by anamika-yadav99** [comment]
Regex works fine. It's the wrong tree which should be removed.

**Comment by manulera** [comment]
hhmm you are right. I wonder why though the tree should only be substituted if changes are made, and regex are matched. One error for sure is line 99:

```
if updated_tree != allele_tree:
# should be
if updated_tree != output_tree:
```

You can have a look and see if you can fix it. It may have to do with this way of checking whether a match was found (not sure how ParentedTree equality is tested). However, I don't see why the tree should be updated if the regex are not matched: how do we get to either of the options in line 111 when the regex fails?
```python
# Line 111
if outcome == 'match':
    output_tree = updated_tree
elif outcome == 'split parent':
```

**Comment by manulera** [comment]
I can have a look at it myself later, I would suggest to use only the part of that allele that fails and see if you can figure out where it fails.

**Comment by anamika-yadav99** [comment]
> hhmm you are right. I wonder why though the tree should only be substituted if changes are made, and regex are matched. One error for sure is line 99:
> 
> ```
> if updated_tree != allele_tree:
> # should be
> if updated_tree != output_tree:
> ```
> 
> You can have a look and see if you can fix it. It may have to do with this way of checking whether a match was found (not sure how ParentedTree equality is tested). However, I don't see why the tree should be updated if the regex are not matched: how do we get to either of the options in line 111 when the regex fails?
> 
> ```python
> # Line 111
> if outcome == 'match':
>     output_tree = updated_tree
> elif outcome == 'split parent':
> ```

There will be one more condition here if the match is found then sure go ahead and return but if outcome =='no match' then the tree should be deleted and all the leaves will have to be inserted back at the same position. 

Line 99 is correct. Updated tree will not be equal to allele tree if parser identifies <other><GENE>.

**Comment by manulera** [comment]
Hi Anamika,

The line 99 is incorrect as is. allele_tree is the original input, and it never gets updated, the one that updates is the output_tree (incorporates new chunks found with the rules).

There is no need to delete trees, as output_tree should only be updated if the conditions are met.

**Pull request merged**
