### PR TITLE
Solves issue #40 - Small API

### PR DESCRIPTION
**Pull request by riddhisera**
#### Replaces the function `your_function` with `name2pattern` that takes the allele name and returns the pattern.

The code here derives from the code in the function build_nltk_tag, in the`build_nltk_tags.py` file.  The code was rewritten (with some modifications) instead of being imported to avoid changes to the `build_nltk_tags.py` file. For example, the function `build_nltk_tag` takes in a list while the input here is a string so the for loop in line 94 was avoided. 

One of the .toml files was missing ('allele_components/tags_fpbase.toml') so I had to comment it to avoid errors.

I also had to create the `read_strains_tsv.py` file since `api.py` threw the following error: `ImportError: cannot import name 'read_strains_tsv' from 'genestorian_module' (unknown location)`

### CODE REVIEW

**Comment by anamika-yadav99** [comment]
Hi @riddhisera  to get 'allele_components/tags_fpbase.toml' file you need to run `python get_fpbase_data.py ../allele_components/tags_fpbase.toml `  in the correct directory. This would save a file in allele_components directory. I'm not sure why read_strains_tsv is throwing an error because it works in my case. Have you managed to run other scripts? We have used nbrp strains a example to demonstrate.

**Comment by manulera** [comment]
Hello! I see you two are already discussing how to do it, that's great. I am quite busy this week but I will try to have a look.

**Comment by riddhisera** [comment]
Thank @anamika-yadav99! I solved both issues by running `python get_fpbase_data.py ../allele_components/tags_fpbase.toml` and `pip install -e genestorian_module`. Yes, I managed to run the other scripts as well. 

I wanted to know if you would prefer I change the `build_nltk_tag` function to be compatible with strings so I can import it to api.py instead of having to rewrite the same code in `name2pattern`. (I think this would also require some changes in other functions as well)

**Comment by manulera** [comment]
Hi @riddhisera thanks for having a go at this. Here are some suggestions. As you point out it's better practice to re-use the code. My advice would be to aim for something like this:

```python
toml_files = [
        'data/alleles.toml',
        'data/gene_IDs.toml',
        'allele_components/tags.toml',
        'allele_components/tags_fpbase.toml',
        'allele_components/markers.toml',
        'allele_components/promoters.toml',
        'allele_components/sequence_features.toml'
]
# Note the .lower(), this is important for matching the strings
alleles_list = build_nltk_tag([allele_name.lower()], toml_files)

# Some extra code to get the pattern only
```

For this to work:

* The path of `allele_components/separators.txt` could be passed as a function argument to `build_nltk_tag`, and then passed as an argument to `build_separators_dict` which currently has the path hard-coded.
* To not break the existing code, you can make this an optional function argument of both `build_nltk_tag` and `build_separators_dict` which defaults to the hard-coded value.

Finally, regarding this:
>  and pip install -e genestorian_module. Yes, I managed to run the other scripts as well.

Did you check the [installation instructions](https://github.com/manulera/genestorian_data_refinement#installing)? If you use poetry you should not have any problem with dependencies. The only thing is that you should do `poetry install` when you are in the api branch.

Finally, full disclosure about GSoC this year. I am not sure I will be joining as I am really busy with work, but I am happy to have a call if you want to discuss what your interests are or if you want some advice for applying this year. You can write to me at my email, which is here: https://www.ucl.ac.uk/biosciences/people/dr-manuel-lera-ramirez

**Comment by riddhisera** [comment]
Hi @manulera! Thank you, I have made the suggested changes and checked if the code works in its default use case using the ` python build_nltk_tags.py ../../Lab_strains/nbrp_strains/strains.tsv` command and in the API. 

I did run `poetry install` in the api branch by following the installation instructions. But I am still not sure why I needed to pip install `genestorian_module`.

As for GSOC, I would love your advice in applying this year. My contribution to this project is only out of pure interest. I shall reach out to you soon. Thanks!

**Review by manulera — APPROVED** [review]
All good! I fixed a small typo in the var name, but looks great. Thanks @riddhisera 🚀🚀🚀

**Pull request merged**
